[wokwi]
version = 1
firmware = './build/firmware/ESP32_GENERIC-20241129-v1.24.1.bin'
elf = './build/firmware/ESP32_GENERIC-20231005-v1.21.0.elf'

[[chip]]
name = 'soil-sensor'  # To use the chip in diagram.json, add a part with "chip-inverter" type.
binary = 'chips/soil-sensor.chip.c'

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"